language: node_js
node_js:
- stable
after_success:
- npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: davidcsally@gmail.com
  api_key:
    secure: PHGcVF5IkVMuCktt29Ky3GtNEytNOtBlqVQCbvsvCIYTRBqiKVy5ZBw8yntj/m8l5RfH7Rw8eD5q7be47RegRrb2LTMEIpEcKV/6tugRZ0UrJB5QqV+UrPj3uUA37o8z8OjQEQkLbGim/MaQHgqe947pERDytlOZ12bKBEeJUlVwVbsKx3G1pwNtp7U1X7Ry/j5io7HRWavMQUvvA8lbIC1G8pF253I+Mf5a5NxJOglxq2Us9DQg/co7F4yv91YIQ0oeRgyYiecoGbxg78o9Tr615TBpHpWXgv2nss4lUOWD0SUtkcBlWOfOIv8b9P6hSOLaEPN67hlAGhK3fvUiz2shcFzFQWDGE8LZRNo2U8JAi8+HavmwE9mvO5PaaGEgGI4fFUryhGVlh86sQKhohxjXWNAntVoUkoD++15trXYA6bMHpHT8HnjQv7YfLqUR5gapZnHee/RiC6sVYwV49LOU1E14J03hM0eIGQdU5TEhbq10139WbURWq0aXDjQX+SENLQlL0Jct1UnfDXAv4N2enFFbkMfIt5bDNaltSokCPUM6AzLmMsM5Ikb/7ozGC7eYgpPaWIqZXWaQ3vdf+9f8yv3Mm+TX5LBLugPNBkHrh4h9OtxXIaAdxkqYe+3I18wSGPGvevTMuG9KA2ux9xZAgYZAGqhYJj0n0Ag9jsM=
  on:
    repo: davidcsally/node-progress-bar
    branch: production
    skip_cleanup: true
